// desafio02/src/app/login/login.component.ts
import { Component, OnInit, NgZone } from '@angular/core'
import { FormBuilder, Validators } from '@angular/forms'
import { AngularFireAuth } from '@angular/fire/auth'
import { Router } from '@angular/router'
import { auth } from 'firebase'
import { ToastService } from '../toast/toast.service'

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  constructor(
    private afAuth: AngularFireAuth,
    private router: Router,
    private formB: FormBuilder,
    private ngZone: NgZone,
    private toast: ToastService,
  ) { }

  loginForm = this.formB.group({
    email: ['', Validators.required],
    password: ['', Validators.required],
  })

  checkField(field: string) {
    return this.loginForm.controls[field].touched && this.loginForm.controls[field].errors?.required
  }

  ngOnInit() {
    this.afAuth.user.subscribe(user => {
      if (user) {
        this.toast.show("Logueado!!", "success")
        this.ngZone.run(() => this.router.navigate(['/records']))
      }
    })
  }

  signUp() {
    this.afAuth.signInWithPopup(new auth.GoogleAuthProvider())
      .then(() => {
        this.toast.show("Logueado!!", "success")
        this.router.navigate(['/records'])
      })
      .catch(err => this.toast.show(err.message, "error"))
  }

  createUser() {
    this.afAuth.createUserWithEmailAndPassword(this.loginForm.value.email, this.loginForm.value.password)
      .then(() => {
        this.toast.show("Logueado!!", "success")
        this.router.navigate(['/records'])
      })
      .catch(err => this.toast.show(err.message, "error"))
  }

  signIn() {
    this.afAuth.signInWithEmailAndPassword(this.loginForm.value.email, this.loginForm.value.password)
      .then(() => {
        this.toast.show("Logueado!!", "success")
        this.router.navigate(['/records'])
      })
      .catch(err => this.toast.show(err.message, "error"))
  }
}

<div class="form-login">
  <button type="button" (click)="signUp()" class="d-block btn btn-primary mx-auto">Continuar con Google</button>
  <hr class="w-75 text-dark mx-auto mb-3" />


  <form [formGroup]="loginForm">
    <div class="form-group">
      <label for="email">Correo</label>
      <input formControlName="email" id="email" type="text" placeholder="Correo electronico" class="form-control" />
      <span *ngIf="checkField('email')" class="text-danger">El correo es requerido.</span>
    </div>

    <div class="form-group">
      <label for="password">Contraseña</label>
      <input formControlName="password" id="password" type="password" placeholder="Password" class="form-control" />
      <span *ngIf="checkField('password')" class="text-danger">La contraseña es requerida.</span>
    </div>

    <div class="d-flex justify-content-center mt-3">
      <button type="button" (click)="signIn()" class="btn btn-primary mr-3">Log in</button>
      <button type="button" (click)="createUser()" class="btn btn-success">Create Account</button>
    </div>
  </form>
</div>

// desafio03/src/views/LogIn.tsx
import React, { FormEvent, useState } from "react";
import { useRouter } from "react-router5";

import firebase, { Auth } from "../plugins/firebase";
import Toast from "../plugins/Toastr";

export default function LogIn() {
  const { navigateToDefault } = useRouter();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  function ToastAndRedirect() {
    Toast.show("Logueado!!", "success");
    navigateToDefault();
  }
  if (Auth.currentUser) ToastAndRedirect();

  const withGoogle = () => {
    Auth.signInWithPopup(new firebase.auth.GoogleAuthProvider())
      .then(ToastAndRedirect)
      .catch(Toast.error);
  };

  const withEmail = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    Auth.signInWithEmailAndPassword(email, password)
      .then(ToastAndRedirect)
      .catch((err) => {
        err.code !== "auth/user-not-found"
          ? Toast.error(err)
          : Auth.createUserWithEmailAndPassword(email, password)
              .then(ToastAndRedirect)
              .catch(Toast.error);
      });
  };

  return (
    <section
      className="row justify-content-center mt-5"
      style={{ minWidth: "260px" }}
    >
      <div className="w-100">
        <button
          type="button"
          onClick={withGoogle}
          className="d-block btn btn-primary mx-auto"
        >
          Continuar con Google
        </button>
        <hr className="w-75 text-dark mx-auto mb-3" />
        <form onSubmit={withEmail}>
          <div className="form-group">
            <label htmlFor="email">Correo</label>
            <input
              type="email"
              value={email}
              placeholder="Correo electronico"
              className="form-control"
              onChange={(e) => setEmail(e.target.value)}
            />
          </div>
          <div className="form-group">
            <label htmlFor="password">Contraseña</label>
            <input
              type="password"
              value={password}
              placeholder="Contraseña"
              className="form-control"
              onChange={(e) => setPassword(e.target.value)}
            />
          </div>
          <div className="d-flex justify-content-center mt-3">
            <button type="submit" className="btn btn-outline-primary">
              Continuar con correo y contraseña
            </button>
          </div>
        </form>
      </div>
    </section>
  );
}
